#!/bin/bash

_dake() {
#	local cur=${COMP_WORDS[COMP_CWORD]}

    local cur
    local words
    local cword
    _get_comp_words_by_ref -n : cur words cword

#    echo "-----dake __completion__ ${cword} ${words[@]:1}-----"

    result=$(dake __completion__ ${cword} ${words[@]:1})

    special=$(echo "$result" | egrep "::[a-z]+::$" > /dev/null ; echo $?);

    if [ $special == 0 ]; then
        special=$(echo "$result" | sed "s/::\(.\+\)::/\1/g")
        case "$special" in
            "file")
                _filedir
                ;;
            "dir")
                _filedir -d
                ;;
        esac
        return 0
    fi

    COMPREPLY=( $(compgen -W "$result" -- "$cur") )

    __ltrim_colon_completions "$cur"
    return 0
}

complete -F _dake dake
